import { DefaultTheme } from 'vitepress';

export function sidebarModelFunctions(): DefaultTheme.SidebarItem[] {
  return [{
    text: 'model functions',
    base: '/model-functions',
    items: [
      {text: 'Function Attach', link: '/attach'},
      {text: 'Function Chunk', link: '/chunk'},
      {text: 'Function ChunkById', link: '/chunkById'},
      {text: 'Function Count', link: '/count'},
      {text: 'Function Create', link: '/create'},
      {text: 'Function CreateQuery', link: '/createQuery'},
      {text: 'Function Delete', link: '/delete'},
      {text: 'Function DoesntExist', link: '/doesntExist'},
      {text: 'Function Each', link: '/each'},
      {text: 'Function EachById', link: '/eachById'},
      {text: 'Function Fillable', link: '/fillable'},
      {text: 'Function Find', link: '/find'},
      {text: 'Function FindOrFail', link: '/findOrFail'},
      {text: 'Function FindOrNew', link: '/findOrNew'},
      {text: 'Function First', link: '/first'},
      {text: 'Function FirstOrCreate', link: '/firstOrCreate'},
      {text: 'Function FirstOrNew', link: '/firstOrNew'},
      {text: 'Function FormatISO', link: '/formatISO'},
      {text: 'Function ForPageAfterId', link: '/forPageAfterId'},
      {text: 'Function Fresh', link: '/fresh'},
      {text: 'Function FromDateTime', link: '/fromDateTime'},
      {text: 'Function FromQuery', link: '/fromQuery'},
      {text: 'Function GetAttribute', link: '/getAttribute'},
      {text: 'Function GetConnectionName', link: '/getConnectionName'},
      {text: 'Function GetCountForPagination', link: '/getCountForPagination'},
      {text: 'Function GetQuery', link: '/getQuery'},
      {text: 'Function GetRelation', link: '/getRelation'},
      {text: 'Function GroupBy', link: '/groupBy'},
      {text: 'Function Has', link: '/has'},
      {text: 'Function Head', link: '/head'},
      {text: 'Function InitAttributes', link: '/initAttributes'},
      {text: 'Function Insert', link: '/insert'},
      {text: 'Function Is', link: '/is'},
      {text: 'Function IsIgnoringTouch', link: '/isIgnoringTouch'},
      {text: 'Function IsNumber', link: '/isNumber'},
      {text: 'Function Join', link: '/join'},
      {text: 'Function Match', link: '/match'},
      {text: 'Function Max', link: '/max'},
      {text: 'Function Min', link: '/min'},
      {text: 'Function MorphMap', link: '/morphMap'},
      {text: 'Function NewQuery', link: '/newQuery'},
      {text: 'Function NewRelation', link: '/newRelation'},
      {text: 'Function Oldest', link: '/oldest'},
      {text: 'Function Paginate', link: '/paginate'},
      {text: 'Function Pluck', link: '/pluck'},
      {text: 'Function Save', link: '/save'},
      {text: 'Function SaveOrFail', link: '/saveOrFail'},
      {text: 'Function Select', link: '/select'},
      {text: 'Function SetConnection', link: '/setConnection'},
      {text: 'Function SetDateFormat', link: '/setDateFormat'},
      {text: 'Function SetRawAttributes', link: '/setRawAttributes'},
      {text: 'Function StartOfSecond', link: '/startOfSecond'},
      {text: 'Function ToArray', link: '/toArray'},
      {text: 'Function ToJSON', link: '/toJSON'},
      {text: 'Function ToSql', link: '/toSql'},
      {text: 'Function ToThrowError', link: '/toThrowError'},
      {text: 'Function Update', link: '/update'},
      {text: 'Function UpdateOrCreate', link: '/updateOrCreate'},
      {text: 'Function UseConnection', link: '/useConnection'},
      {text: 'Function Where', link: '/where'},
      {text: 'Function WhereColumn', link: '/whereColumn'},
      {text: 'Function WhereHas', link: '/whereHas'},
      {text: 'Function With', link: '/with'},
    ]
  }]
}