import { DefaultTheme } from 'vitepress';

export function sidebarModelFunctions(): DefaultTheme.SidebarItem[] {
  return [
    {
      text: 'Querying',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'createQuery', link: '/createQuery'},
        {text: 'newQuery', link: '/newQuery'},
        {text: 'where', link: '/where'},
        {text: 'whereColumn', link: '/whereColumn'},
        {text: 'whereHas', link: '/whereHas'},
        {text: 'has', link: '/has'},
        {text: 'with', link: '/with'},
        {text: 'select', link: '/select'},
        {text: 'join', link: '/join'},
        {text: 'groupBy', link: '/groupBy'},
        {text: 'oldest', link: '/oldest'},
      ],
    },
    {
      text: 'Reading One Row',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'find', link: '/find'},
        {text: 'findOrFail', link: '/findOrFail'},
        {text: 'findOrNew', link: '/findOrNew'},
        {text: 'first', link: '/first'},
        {text: 'firstOrNew', link: '/firstOrNew'},
        {text: 'firstOrCreate', link: '/firstOrCreate'},
        {text: 'fresh', link: '/fresh'},
      ],
    },
    {
      text: 'Reading Many Rows',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'paginate', link: '/paginate'},
        {text: 'pluck', link: '/pluck'},
        {text: 'count', link: '/count'},
        {text: 'max', link: '/max'},
        {text: 'min', link: '/min'},
      ],
    },
    {
      text: 'Iterating Large Result Sets',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'chunk', link: '/chunk'},
        {text: 'chunkById', link: '/chunkById'},
        {text: 'each', link: '/each'},
        {text: 'eachById', link: '/eachById'},
        {text: 'forPageAfterId', link: '/forPageAfterId'},
        {text: 'getCountForPagination', link: '/getCountForPagination'},
      ],
    },
    {
      text: 'Writing',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'create', link: '/create'},
        {text: 'insert', link: '/insert'},
        {text: 'save', link: '/save'},
        {text: 'saveOrFail', link: '/saveOrFail'},
        {text: 'update', link: '/update'},
        {text: 'updateOrCreate', link: '/updateOrCreate'},
        {text: 'delete', link: '/delete'},
      ],
    },
    {
      text: 'Attributes',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'fillable', link: '/fillable'},
        {text: 'getAttribute', link: '/getAttribute'},
        {text: 'setRawAttributes', link: '/setRawAttributes'},
        {text: 'initAttributes', link: '/initAttributes'},
        {text: 'toArray', link: '/toArray'},
        {text: 'toJSON', link: '/toJSON'},
        {text: 'toSql', link: '/toSql'},
      ],
    },
    {
      text: 'Connections',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'useConnection', link: '/useConnection'},
        {text: 'setConnection', link: '/setConnection'},
        {text: 'getConnectionName', link: '/getConnectionName'},
      ],
    },
    {
      text: 'Relations',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'newRelation', link: '/newRelation'},
        {text: 'getRelation', link: '/getRelation'},
        {text: 'attach', link: '/attach'},
        {text: 'morphMap', link: '/morphMap'},
      ],
    },
    {
      text: 'Identity & Conversion',
      collapsed: false,
      base: '/model-functions',
      items: [
        {text: 'is', link: '/is'},
        {text: 'isNumber', link: '/isNumber'},
        {text: 'isIgnoringTouch', link: '/isIgnoringTouch'},
        {text: 'match', link: '/match'},
        {text: 'head', link: '/head'},
        {text: 'fromQuery', link: '/fromQuery'},
        {text: 'fromDateTime', link: '/fromDateTime'},
        {text: 'formatISO', link: '/formatISO'},
        {text: 'startOfSecond', link: '/startOfSecond'},
        {text: 'setDateFormat', link: '/setDateFormat'},
        {text: 'doesntExist', link: '/doesntExist'},
        {text: 'getQuery', link: '/getQuery'},
        {text: 'toThrowError', link: '/toThrowError'},
      ],
    },
  ];
}
